### ISSUE TITLE
[3w] 이벤트 버블링

### ISSUE THREAD

**Issue by sookyeonghwang** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#10]
- [ ] 이벤트 버블링이란 무엇인가요? 어떻게 막을 수 있나요?
- [ ] 이벤트 버블링와 이벤트 캡쳐링의 차이는 무엇인가요?

**Comment by aurora32s** [comment]
- [ ] 이벤트를 등록할 때 이벤트 캡쳐링을 캐치하기 위해서는 어떻게 해야 하나요?
- [ ] 이벤트 위임(delegation)이란?
- [ ] currentTarget과 target의 차이점은 무엇인가요?

**Comment by Outwater** [comment]
- [ ] 이벤트 전파를 막기 위한 방법은 ?
- [ ] e.preventDefault() 와 e.stopPropagation 의 차이는?

**Comment by Miral3** [comment]
~`event.stopPropagation()` 와 `event.preventDefault()`를 동시에 사용려면 어떻게 해야할까요?~
event handler에 false를 반환하면 위와같은 동작이 일어나는줄 알았는데 jQuery 기준이네요 😭
false를 반환하면 e.preventDefault()와 같은 동작을 합니다!
- [ ] `event.stopPropagation()`와 `event.stopImmediatePropagation()`의 차이는 무엇일까요?
- [ ] 커스텀 이벤트는 무엇이고 왜 사용할까요?

**Comment by loopy-dev** [comment]
- [x] 이벤트 델리게이션 패턴을 사용하는 이유와 구체적인 예를 들어 설명해주세요.

**Comment by ryong9rrr** [comment]
- [ ] 실제로 개발상에서 이벤트 위임 패턴을 사용해보신적이 있나요? 있다면 왜 사용하셨나요? (준혁님의 질문과 비슷한 맥락)

**Comment by sookyeonghwang** [comment]
[이벤트 전파와 위임 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Javascript/%EC%9D%B4%EB%B2%A4%ED%8A%B8%EC%A0%84%ED%8C%8C%EC%99%80%EC%9C%84%EC%9E%84.md)
