### ISSUE TITLE
[3w] HTTP, HTTPS

### ISSUE THREAD

**Issue by sookyeonghwang** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#11]
- [ ] HTTP가 무엇인가요?
- [ ] HTTP 버전의 발전 과정을 설명해보세요.
- [ ] HTTP와 HTTPS 프로토콜의 차이점은 무엇인가요?

**Comment by Outwater** [comment]
- [ ] HTTP status를 알고 있는만큼 말해주세요.
- [ ] HTTPS는 왜 등장하게 되었나요?
- [ ] HTTPS 암호화 과정에 대하여 말해주세요.
  - keyword: `SSL`, `공개키암호화방식(비대칭키)`, `공통키암호화방식`, `CA 증명서`
- [ ] SSL/TSL 프로토콜이 가지는 장점은 무엇인가요?

**Comment by loopy-dev** [comment]
- [ ] 비대칭키 암호화 과정에서 발생하는 단점은 https에서 어떤 방식으로 극복하고 있나요?

**Comment by aurora32s** [comment]
- [ ] HTTP 1.1과 HTTP2.0의 차이점은 무엇인가요?
- [ ] HTTP 3도 아시나요? 무엇인가요?

**Comment by ryong9rrr** [comment]
- [ ] HTTP 메서드에 대해서 알고 있는만큼 말해주세요.

**Comment by sookyeonghwang** [comment]
[http 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/http.md)
[https 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/https.md)
