### ISSUE TITLE
[3w] RESTful

### ISSUE THREAD

**Issue by sookyeonghwang** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#12]
- [ ] RESTful 이 무엇인가요?

**Comment by Outwater** [comment]
- [ ] Rest API의 일반적인 설계 규칙에 대해서 말해주세요.
- [ ] REST API의 장단점은 무엇인가요? 
- [ ] graphQL을 이용한 API 방식과 비교하여 REST API를 설명해주세요.

**Comment by ryong9rrr** [comment]
- [ ] REST API를 만들어보신적이 있나요? 있다면 그 경험에 대해서 말씀해주세요. (경험이 없으셔도 괜찮습니다)

**Comment by Outwater** [comment]
[내용확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/Rest.md)
