### ISSUE TITLE
[4w] 실행컨텍스트

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#15]
실행컨텍스트 관련 질문 리스트 업 합니다.
- [ ] 실행컨텍스트는 언제 생성되나요?
- [ ] 실행컨텍스트는 어떤 정보를 포함하고 있나요?
- [ ] 실행컨텍스트를 아는 것이 왜 중요한가요?
- [ ] 클로저의 동작를 실행컨텍스트 개념을 활용하여 설명해주세요.
- [ ] lexicalEnvironment( 어휘적환경 || 정적확경 || 사전적환경 )에 대해 설명해주세요.
- [ ] 스코프체인에 대해서 설명해주세요.

**Comment by sookyeonghwang** [comment]
[실행 컨텍스트 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Javascript/%EC%8B%A4%ED%96%89%EC%BB%A8%ED%85%8D%EC%8A%A4%ED%8A%B8.md)
