### ISSUE TITLE
[4w] CSS 

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#16]
이번주 데브코스에서 배운 CSS 관련 면접 질문을 리스트업 해주세요.

**Comment by loopy-dev** [comment]
- [ ] `flex`와 `grid`의 특징 및 차이점? ~~2분전에 올린걸 캐치했다~~

**Comment by Outwater** [comment]
### 면접주제 변경으로 Close합니다.
