### ISSUE TITLE
[4w] SPA & SSR

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#23]
`SPA`, `CSR & SSR` 관련 질문을 리스트업 합니다!

**Comment by ryong9rrr** [comment]
SPA는 왜 등장하게 되었을까요? `등장배경`
-> 관련 영상을 찾다가 화랑님의 유튜브 영상을 발견!! https://www.youtube.com/watch?v=C6uELkDh-60
-> 우테코 10분 테코톡 <주모님의 SPA> https://www.youtube.com/watch?v=vM_zQLnlyKw&t=22s

**Comment by Outwater** [comment]
#### 중요ref
 - 3편 시리즈로 SSR 도입과정을 다루고 있습니다. 내용이 조금 길지만, SSR CSR 차이부터 SSR의 장점을 실제 실무적인 부분과 함께 공부할 수 있습니다. [Naver D2- 어서와 SSR은 처음이지?](https://d2.naver.com/helloworld/7804182)

#### 질문리스트
- [ ] SSR (Server Side Rendering) 과 CSR (Client Side Rendering)을 각각 설명해주세요. `특징` `장단점`
  - [ ] 본인이 어떤 프로젝트를 진행할 때, SSR과 CSR 중 어떤 것을 선택하였고, 선택이유는 무엇인가요? 
- [ ] SSR과 CSR을 중심으로, 렌더링 관점에서의 흐름 변화를 말해주세요.
- [ ] SPA (Single Page Application) 와 CSR (Client Side Rendering) 은 같은 개념인가요?
  - [ ] 다르다면 차이점을 중심으로 설명해주세요.
- [ ] SPA 의 단점을 말하고, 해결하기 위한 방법에 대해서 말씀해주세요 `lazy loading`

**Comment by sookyeonghwang** [comment]
- [ ] SPA(Single Page Application)와 MPA(Multi Page Application)을 각각 설명해주세요. 
- [ ] SEO(검색 엔진 최적화)는 무엇인가요?
  - [ ] SEO는 CSR과 SSR 방식 중 어느 방식으로 주로 사용되나요? `이유`
  - [ ] SPA에서 SEO에 유리하도록 만들기 위한 방법에 대해 설명해주세요.

**Comment by loopy-dev** [comment]
@sukyeongh 수경님 SPA에서 SEO에 유리하도록 만드는 방법을 찾아봤는데 저는 못찾은 것 같아요. 혹시 생각하고 계신 답이 있나요?

**Comment by Outwater** [comment]
@mrbartrns 제대로 찾아보지는 않았는데, preRendering방식으로 meta태그를 렌더링 이전에 검색엔진에 넣어줄 수 있다고 하는 것 같아요. react에서는 react-helmet 라이브러리 통해 가능한 것 같네용 ~ [관련링크](https://smartsolar.tistory.com/entry/SPASingle-Page-Application-SEO-%EB%B0%A9%EB%B2%95-%EC%A0%95%EB%A6%AC-by-%EB%B9%84%EA%B0%9C%EB%B0%9C%EC%9E%90)

**Comment by sookyeonghwang** [comment]
> @sukyeongh 수경님 SPA에서 SEO에 유리하도록 만드는 방법을 찾아봤는데 저는 못찾은 것 같아요. 혹시 생각하고 계신 답이 있나요?

엇 SEO 관련해서 찾다가 FE 면접 질문을 모아놓은 사이트 [여기](http://yoonbumtae.com/?p=2445)에서 찾았고 아래와 같은 대답을 보았습니다!
<img width="888" alt="image" src="https://user-images.githubusercontent.com/50071076/166417623-2ba0445f-edf3-4c64-bf8e-d27895184f10.png">

질문이 괜찮은지는 잘 모르겠네요ㅠ😭

**Comment by loopy-dev** [comment]
- [ ] SPA 에서 SSR을 구현할 수 있는 방법이 있나요? 있다면, 장점은 무엇인가요?
- [ ] 왜 이러한 트렌드로 넘어가게 되었나요? (다른 분들의 질문과 비슷한 결입니다)
>Next.js 작동 원리 (대표적인 SPA on SSR이기 때문에 개념만 참조하시면 될 것 같습니다.)
> 1. 초기에 사용자가 Server에 페이지 접속을 요청하면, SSR방식으로 렌더링 될 HTML을 보냄.(Next.js에서 모든 페이지가 사용자에게 전해지기 전에 HTML을 미리 생성해 Pre-Rendering을 수행)
> 2. 브라우저에서 JavaScript를 다운로드하고 React를 실행함.
> 3. 사용자, 페이지가 서로 상호작용하여 다른 페이지로 이동할 땐, Server가 아닌 CSR방식으로 브라우저에서 처리함.

**Comment by sookyeonghwang** [comment]
[CSR, SSR 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/CSRvsSSR.md)
