### ISSUE TITLE
[5w] 정렬

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#24]
정렬 관련 질문 작성해주세요.

**Comment by sookyeonghwang** [comment]
- [ ] 54321 배열을 12345로 정렬 할 때 어떤 sort를 사용할 것인가요? `이유`
- [ ] random으로 배열된 숫자들이 있을 때 어떤 sort를 사용할 것인가요? `이유`
- [ ] selection sort가 일어나는 과정을 설명해보세요.
- [ ] insertion sort가 일어나는 과정을 설명해보세요.
- [ ] bubble sort가 일어나는 과정을 설명해보세요.
- [ ] merge sort가 일어나는 과정을 설명해보세요.
- [ ] quick sort가 일어나는 과정을 설명해보세요.

**Comment by loopy-dev** [comment]
- 선택 정렬
- 버블 정렬
- 삽입 정렬
- 합병 정렬
- 퀵 정렬

최선, 최악, 평균 시간복잡도 및 메모리복잡도

[Tim sort에 대해 알아보자 (naver.com)](https://d2.naver.com/helloworld/0315536)

**Comment by ryong9rrr** [comment]
준혁님이 팀소트 언급하신것보고 갑자기 생각났네요 ㅎㅎ 팀소트에 대해 조금이라도 알고있으면 좋을 것 같습니다.

- [ ] 자바스크립트 sort 메서드는 어떤 알고리즘으로 설계되었나요? 
(브라우저마다 다릅니다! v8 엔진은 팀소트를 사용합니다. 출처 : https://github.com/v8/v8/blob/78f2610345fdd14ca401d920c140f8f461b631d1/third_party/v8/builtins/array-sort.tq#L5 ) 

- [ ] 팀소트 알고리즘에 대해서 조금 설명해주실 수 있나요?
- [ ] 안정정렬과 불안정정렬에 대해서 설명해주세요.

**Comment by Outwater** [comment]
[정렬_기본](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/CS/%EC%A0%95%EB%A0%AC.md)
[정렬_심화](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/CS/%EC%A0%95%EB%A0%AC(%EC%8B%AC%ED%99%94).md)
