### ISSUE TITLE
브라우저 저장소

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#6]
1depth
- 12
- 12

2depth
- ㄹ

**Comment by sookyeonghwang** [comment]
[브라우저 저장소 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EC%A0%80%EC%9E%A5%EC%86%8C.md)
