### ISSUE TITLE
[2w] 브라우저 렌더링

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#7]
- [ ] 브라우저에 특정한 URL을 입력하면 발생하는 각각의 단계에서 어떤 일이 발생하는지 알려주세요.
  - `URL 파싱`, `DNS 조회`, `ARP로 MAC주소 변환`, `TCP 통신`, `브라우저 렌더링`
 
- [ ] 브라우저 렌더링 과정을 흐름에 따라 설명해주세요.
  - `HTML파싱`, `CSSOM` , `DOM Tree`, `RenderTree`, `Layout(reflow)`, `Paint`

- [ ] Reflow와 Repaint는 무엇이고, 언제 발생하나요?

**Comment by loopy-dev** [comment]
제가 공부하면서 궁금한게 생겼는데 `문맥 자유 문법`에 대하여 조금 아시는분 계신가요? 검색해도 잘 이해가 안되네요 ㅜㅜ

**Comment by Outwater** [comment]
> 제가 공부하면서 궁금한게 생겼는데 `문맥 자유 문법`에 대하여 조금 아시는분 계신가요? 검색해도 잘 이해가 안되네요 ㅜㅜ

html 파싱과정에서 html이 `문맥 자유 문법` 이다. 라는 부분에서 나온 부분 맞나요?
제가 이해한 바로는 문맥자유는 좌변이 고정되고 우변은 자유로운 상태를 갖는다는 것인데,
여기서 좌변은 html의 tag가 될 수 있고, 우변은 태그안의 content라고 볼 수 있어서 문맥자유문법이라는 것이 아닐까요?
<div></div> tag로 이 엘리먼트의 성격을 어느정도 맥락을 규정해놓은 상태에서, content를 통해 의미를 다양화할 수 있는 부분이요.

**Comment by loopy-dev** [comment]
이게 찾으면 식으로만 설명이 되어있어서 무슨뜻인지 잘 몰랐네요ㅎㅎ. 별개로 제가 조사한 바에 의하면 html은 쉽게 정규화 될 수 없어서(정확히 말하면 브라우저가 잘못 중첩된 태그나, 중첩되면 안되는 태그들을 알아서 교정해줌, script의 `document.write()`에 의한 실시간 수정이 발생) 전통적인 파서로 파싱이 불가능하므로 문맥 자유 문법이 아니라고 보았는데 아닌가요?

**Comment by Outwater** [comment]
앗 그러네요. 언뜻 보았는데, ~~인듯하지만 아니다.가 결론이었네요.
[네이버D2블로그-브라우저의동작원리](https://d2.naver.com/helloworld/59361)에서도 준혁님과 같은 이유라 아니라고 보고 있네요.
top-down방식으로 parser수행이 불가능하기 때문인 것 같아요 ㅎ..ㅎ

**Comment by loopy-dev** [comment]
저랑 같은 블로그를 보고 계시는구나ㅋㅋ. 읽으면서 생각나는 질문들 올리겠습니다. 답변 감사합니다!

**Comment by Miral3** [comment]
`자바스크립트 파싱`과 관련된 주제입니다.
- [ ] script 태그를 body 가장 하단에 삽입하는 이유는 무엇일까요?
  - `DOM 조작`, `로딩 시간`
- [ ] script 태그의 `async`, `defer` 어트리뷰트에 대해서 설명해주세요
  - `HTML 파싱 블로킹`, `비동기`

**Comment by loopy-dev** [comment]
reflow, repaint 관련
- [ ] reflow, repaint를 줄일 수 있는 방법은 무엇이 있을까요?
  - reflow, reapint를 일으키는 스타일 사용 줄이기, `virtual DOM` 사용
- [ ] `virtual DOM`을 사용하는 것이 항상 옳을까요?
  - `virtual DOM`의 장단점

**Comment by aurora32s** [comment]
브라우저 렌더링과 관련된 질문 리스트

1. element의 위치가 변경되는 코드가 있을 때, 브라우저는 이 변경을 어떤 순서대로 화면에 반영할까요?

2. 브라우저 로딩 시간을 빠르게 하기 위해 어떤 처리를 할 수 있을까요?
   - async, defer 이라 답한 경우
      - async와 defer의 차이점에 대해서 말해주세요. 

3.

**Comment by sookyeonghwang** [comment]
[브라우저 렌더링 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EB%A0%8C%EB%8D%94%EB%A7%81.md)
[http 통신 과정 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/Web/http.md)
