### ISSUE TITLE
[2w] 해시테이블

### ISSUE THREAD

**Issue by Outwater** [prgrms-web-devcourse/FE-Speak-And-Learn-Study#8]
- [ ] 해시테이블 (Hash Table)에 대해서 간단하게 설명해주세요.
- [ ] 해시함수란 무엇인가요.
- [ ] 해시테이블을 사용하는 이유, 장점에 대해서 설명해주세요.
- [ ] 해시충돌에 대해서 설명해주세요
- [ ] 해시 충돌의 해결 방법에 대해서 설명해주세요.
- [ ] 해시테이블을 활용한 사례가 있다면 알려주세요. 없다면 언제 쓰일 수 있을까요?

**Comment by sookyeonghwang** [comment]
[해시테이블 내용 확인하기](https://github.com/prgrms-web-devcourse/FE-Speak-And-Learn-Study/blob/main/CS/%ED%95%B4%EC%8B%9C%ED%85%8C%EC%9D%B4%EB%B8%94.md)
